DROP TABLE IF EXISTS Trade;
 
CREATE TABLE Trade (
  ID INT   PRIMARY KEY,
  TICKER VARCHAR(250) NOT NULL,
  UNIT_PRICE INT NOT NULL
);

INSERT INTO Trade (ID, TICKER, UNIT_PRICE) VALUES
  (1, 'Wipro', 180),
  (2, 'TCS', 220),
  (3, 'Infosys', 180);